// Project Eular

/* Problem 1 

If we list all the numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. 
The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.*/

var array = []; 

for (var i = 0; i < 1000; i++) {
	if (i % 3 === 0 || i % 5 === 0) {
		array.push(i); 
	}	
}

var sum = 0;

for (var i = 0; i < array.length; i++){
	sum += array[i]; 	 
}

console.log('Problem 1: ', sum); 

// What is the middle number of the array? 

var middleIndex; 
var value; 

function findMiddleIndex(){
	var length = array.length; 
	middleIndex = Math.round(length/2) - 1;
	value = array[middleIndex]; 
}

findMiddleIndex(); 

console.log('Middle index: ', value);

/* Problem 2 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
var array = []; 

for (var i=1; i<=4000000; i++){
	if (i < 2)
	array.push(i)
}
